config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resource :sessions
end

app/models/picture.rb
class Picture

  attr_accessor :image_url, :date, :location

  def initialize(picture_data)
    @image_url = picture_data[:image_url]
    @date = picture_data[:date]
    @location = picture_data[:location]
  end

end

app/models/user.rb
class User

  attr_accessor :access_token, :username, :profile_picture

  def self.build_from_instagram_response(response)
    user_data = response["user"]
    self.new(access_token: response["access_token"], username: user_data["username"], profile_picture: user_data["profile_picture"])
  end

  def self.build_from_session(session)
    self.new(access_token: session["access_token"], username: session["username"], profile_picture: session["profile_picture"])
  end

  def initialize(access_token:, username:, profile_picture:)
    @access_token = access_token
    @username = username
    @profile_picture = profile_picture
  end

  def to_session
    { access_token: @access_token, username: @username, profile_picture: @profile_picture }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include InstagramSessionHelper
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if logged_in?
      @user = current_user
      @pictures = GetUserPictures.new(@user).execute
    else
      @url = APP_CONFIG::INSTAGRAM::AUTHORIZE_URL
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def show
    user = LoginWithInstagramCode.new(params[:code]).execute
    log_in(user)
    redirect_to root_path
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instagram_session_helper.rb
module InstagramSessionHelper

  def log_in(user)
    session[:user_session] = user.to_session
  end

  def current_user
    @current_user ||= User.build_from_session(session[:user_session])
  end

  def logged_in?
    session[:user_session].present?
  end

  def log_out
    @current_user = nil
    session.delete(:user_session)
  end

end

app/views/home/_galery.html.erb
<div class="tz-gallery">
  <div class="row">
    <% @pictures.each do | pic | %>
      <div class="col-md-6 col-lg-4">
        <div class="thumbnail">
          <div class="lightbox">
            <%= image_tag pic.image_url, class: "img-fluid" %>
          </div>
          <div class="caption">
            <p><%= pic.location %></p>
            <p><%= l pic.date, format: :short %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/home/index.html.erb
<div class="container-fluid gallery-container">
  <h1>ShowoffGram</h1>
  <p class="page-description text-center">An example of Instagram integration</p>
  <% if logged_in? %>

    <%= render partial: "galery" %>
  <% else %>
    <div class="mx-auto login-container">
      <%= link_to "Enter with Instagram", @url, class: "btn btn-primary" %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowoffGram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Droid+Sans:400,700'%>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Home", root_path, class: "navbar-text" %>
      <ul class="navbar-nav mr-auto">
      </ul>
      <% if logged_in? %>
        <small class="navbar-text"><%= @user.username %></small>
        <%= image_tag @user.profile_picture,  class: "profile-picture mx-2" %>
        <%= link_to 'Logout', sessions_path, method: :delete, class: "btn btn-sm btn-outline-secondary", data: { confirm: 'Are you sure?' } %>
      <% end %>
    </nav>
    <main>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>